from .html_assets import render_asset_template as _render_asset_template_helper
from .config import (
    DEFAULT_CHAT_MAX_BYTES as _DEFAULT_CHAT_MAX_BYTES,
    DEFAULT_FILE_TRANSFER_MAX_BYTES as _DEFAULT_FILE_TRANSFER_MAX_BYTES,
    MAX_FILE_TRANSFER_MAX_BYTES as _MAX_FILE_TRANSFER_MAX_BYTES,
    MIN_FILE_TRANSFER_MAX_BYTES as _MIN_FILE_TRANSFER_MAX_BYTES,
)

_DASHBOARD_JS_TEMPLATE_PARTS = (
    "dashboard.js.bootstrap.map.setup_emoji.base.tmpl",
    "dashboard.js.bootstrap.map.setup_emoji.catalog.tmpl",
    "dashboard.js.bootstrap.map.setup_emoji.state.constants_core.tmpl",
    "dashboard.js.bootstrap.map.setup_emoji.state.runtime_primary.tmpl",
    "dashboard.js.bootstrap.map.setup_emoji.state.runtime_games_chat.tmpl",
    "dashboard.js.bootstrap.map.setup_emoji.state.runtime_map_history.tmpl",
    "dashboard.js.bootstrap.map.offline_basemap.atlas_prep.tmpl",
    "dashboard.js.bootstrap.map.offline_basemap.atlas_layers.tmpl",
    "dashboard.js.bootstrap.map.offline_basemap.pack_loader.tmpl",
    "dashboard.js.bootstrap.map.offline_basemap.mode_connectivity.tmpl",
    "dashboard.js.bootstrap.map.resize.tmpl",
    "dashboard.js.bootstrap.map.signal_heatmap.primitives_knobs.tmpl",
    "dashboard.js.bootstrap.map.signal_heatmap.scoring.tmpl",
    "dashboard.js.bootstrap.map.signal_heatmap.render_sync.tmpl",
    "dashboard.js.bootstrap.map.wheel.tmpl",
    "dashboard.js.bootstrap.tickers.metrics.core.tmpl",
    "dashboard.js.bootstrap.tickers.metrics.runtime_time.tmpl",
    "dashboard.js.bootstrap.tickers.metrics.theme.tmpl",
    "dashboard.js.bootstrap.tickers.metrics.livemap.tmpl",
    "dashboard.js.bootstrap.tickers.preferences.tmpl",
    "dashboard.js.bootstrap.tickers.controls.settings_ui.tmpl",
    "dashboard.js.bootstrap.tickers.controls.bindings_metric.tmpl",
    "dashboard.js.bootstrap.tickers.controls.preferences_map_lines.tmpl",
    "dashboard.js.bootstrap.tickers.controls.signal_heatmap_controls.tmpl",
    "dashboard.js.bootstrap.shared.chat_time_utils.tmpl",
    "dashboard.js.bootstrap.shared.telemetry_local.tmpl",
    "dashboard.js.bootstrap.shared.ticker_signal_gps.tmpl",
    "dashboard.js.bootstrap.shared.ticker_node_system.tmpl",
    "dashboard.js.bootstrap.shared.radio_status_freshness.tmpl",
    "dashboard.js.chat.state.core.chat.delivery_reactions.telemetry_geo.tmpl",
    "dashboard.js.chat.state.core.chat.delivery_reactions.ack_delivery.tmpl",
    "dashboard.js.chat.state.core.chat.delivery_reactions.reaction_popover.tmpl",
    "dashboard.js.chat.state.core.chat.channels_notifications.tmpl",
    "dashboard.js.chat.state.channels.labels_menu.tmpl",
    "dashboard.js.chat.state.channels.options_controls.tmpl",
    "dashboard.js.chat.state.channels.bindings_modes.tmpl",
    "dashboard.js.chat.state.games.reversi_local.protocol_invites.tmpl",
    "dashboard.js.chat.state.games.reversi_local.board_state.tmpl",
    "dashboard.js.chat.state.games.reversi_local.persistence_refresh.tmpl",
    "dashboard.js.chat.state.games.classic.checkers.helpers_moves.tmpl",
    "dashboard.js.chat.state.games.classic.checkers.state_refresh.tmpl",
    "dashboard.js.chat.state.games.classic.checkers.move_handlers.tmpl",
    "dashboard.js.chat.state.games.classic.checkers.render_status.tmpl",
    "dashboard.js.chat.state.games.classic.checkers.tmpl",
    "dashboard.js.chat.state.games.classic.chess.tmpl",
    "dashboard.js.chat.state.games.classic.wall_chess.tmpl",
    "dashboard.js.chat.state.games.network.board_links.core.tmpl",
    "dashboard.js.chat.state.games.network.board_links.sync_ui.tmpl",
    "dashboard.js.chat.state.games.network.board_links.actions.tmpl",
    "dashboard.js.chat.state.games.network.reversi_link.protocol_sync.tmpl",
    "dashboard.js.chat.state.games.network.reversi_link.move_runtime.tmpl",
    "dashboard.js.chat.state.games.network.reversi_link.render_controls.tmpl",
    "dashboard.js.chat.state.games.network.reversi_link.session_actions.tmpl",
    "dashboard.js.chat.state.games.network.reversi_link.tmpl",
    "dashboard.js.chat.state.games.ui.tmpl",
    "dashboard.js.chat.state.messaging.peers.tmpl",
    "dashboard.js.chat.state.messaging.emoji_search.tmpl",
    "dashboard.js.chat.state.messaging.send_flow.tmpl",
    "dashboard.js.chat.state.messaging.emoji_ui.tmpl",
    "dashboard.js.chat.state.files.protocol.codec_flow.tmpl",
    "dashboard.js.chat.state.files.protocol.ui_send.tmpl",
    "dashboard.js.chat.state.files.protocol.session_state.tmpl",
    "dashboard.js.chat.state.files.frames.collect_state.tmpl",
    "dashboard.js.chat.state.files.frames.rows_build.tmpl",
    "dashboard.js.chat.state.files.frames.ack_match_helpers.tmpl",
    "dashboard.js.chat.state.files.maintenance.ack_frames.tmpl",
    "dashboard.js.chat.state.files.maintenance.outgoing_sessions.tmpl",
    "dashboard.js.chat.state.files.maintenance.runner.tmpl",
    "dashboard.js.chat.state.files.view.tmpl",
    "dashboard.js.chat.events.core.identity.node_self.tmpl",
    "dashboard.js.chat.events.core.identity.favorites_selection.search_dropdowns.tmpl",
    "dashboard.js.chat.events.core.identity.favorites_selection.favorites_state_ui.tmpl",
    "dashboard.js.chat.events.core.identity.favorites_selection.selection_cache.tmpl",
    "dashboard.js.chat.events.core.identity.favorites_selection.topbar_map_title.tmpl",
    "dashboard.js.chat.events.core.identity.favorites_selection.tmpl",
    "dashboard.js.chat.events.core.identity.text_utils.tmpl",
    "dashboard.js.chat.events.core.layout_tables.split_state_loaders.tmpl",
    "dashboard.js.chat.events.core.layout_tables.resizable_columns.tmpl",
    "dashboard.js.chat.events.core.layout_tables.split_state_persist.tmpl",
    "dashboard.js.chat.events.core.layout_tables.tmpl",
    "dashboard.js.chat.events.core.notifications.notices.message_preview_history.tmpl",
    "dashboard.js.chat.events.core.notifications.notices.persist_track.tmpl",
    "dashboard.js.chat.events.core.notifications.notices.notification_counts.tmpl",
    "dashboard.js.chat.events.core.notifications.notices.autodismiss_filters.tmpl",
    "dashboard.js.chat.events.core.notifications.notices.tmpl",
    "dashboard.js.chat.events.core.notifications.menus.tmpl",
    "dashboard.js.chat.events.core.notifications.unread.tmpl",
    "dashboard.js.chat.events.core.navigation.layout.tmpl",
    "dashboard.js.chat.events.core.navigation.splitters.tmpl",
    "dashboard.js.chat.events.core.navigation.tablesort.tmpl",
    "dashboard.js.chat.events.console.session.core.tmpl",
    "dashboard.js.chat.events.console.session.state.tmpl",
    "dashboard.js.chat.events.console.session.interaction.tmpl",
    "dashboard.js.chat.events.console.commands.helpers.tmpl",
    "dashboard.js.chat.events.console.commands.registry.tmpl",
    "dashboard.js.chat.events.console.formatting.tmpl",
    "dashboard.js.chat.events.console.ui.tmpl",
    "dashboard.js.chat.events.settings.state_normalize.cache_identity.tmpl",
    "dashboard.js.chat.events.settings.state_normalize.accessors_extractors.tmpl",
    "dashboard.js.chat.events.settings.state_normalize.normalize_helpers.tmpl",
    "dashboard.js.chat.events.settings.state_normalize.editors_tabs_geo.tmpl",
    "dashboard.js.chat.events.settings.state_normalize.position_map.source_cache_parsing.tmpl",
    "dashboard.js.chat.events.settings.state_normalize.position_map.state_resolution.tmpl",
    "dashboard.js.chat.events.settings.state_normalize.position_map.ui_bootstrap_tiles.tmpl",
    "dashboard.js.chat.events.settings.state_normalize.position_map.input_sync_render.tmpl",
    "dashboard.js.chat.events.settings.state_normalize.render_read.tmpl",
    "dashboard.js.chat.events.settings.channels.table.tmpl",
    "dashboard.js.chat.events.settings.channels.reading.tmpl",
    "dashboard.js.chat.events.settings.channels.parse.tmpl",
    "dashboard.js.chat.events.settings.apply_actions.config.tmpl",
    "dashboard.js.chat.events.settings.apply_actions.modules.tmpl",
    "dashboard.js.chat.events.settings.apply_actions.radio_ops.tmpl",
    "dashboard.js.chat.events.settings.maps_packs.tmpl",
    "dashboard.js.chat.events.settings.bindings.tmpl",
    "dashboard.js.chat.events.map_selection.tmpl",
    "dashboard.js.chat.events.bindings.tmpl",
    "dashboard.js.ui.shared_controls.tmpl",
    "dashboard.js.chat.events.data_views.summary_map.summary.tmpl",
    "dashboard.js.chat.events.data_views.summary_map.map_helpers.tmpl",
    "dashboard.js.chat.events.data_views.summary_map.map_render.tmpl",
    "dashboard.js.chat.events.data_views.nodes_saved.nodes_table.tmpl",
    "dashboard.js.chat.events.data_views.nodes_saved.saved_helpers.tmpl",
    "dashboard.js.chat.events.data_views.nodes_saved.saved_views.tmpl",
    "dashboard.js.chat.events.data_views.charts.zoom_timeline.signal_zoom.tmpl",
    "dashboard.js.chat.events.data_views.charts.zoom_timeline.history_trend_zoom.tmpl",
    "dashboard.js.chat.events.data_views.charts.zoom_timeline.timeline_render.tmpl",
    "dashboard.js.chat.events.data_views.charts.zoom_timeline.signal_timeline.tmpl",
    "dashboard.js.chat.events.data_views.charts.zoom_timeline.tmpl",
    "dashboard.js.chat.events.data_views.charts.signal_online.tmpl",
    "dashboard.js.chat.events.data_views.charts.weekly.states.tmpl",
    "dashboard.js.chat.events.data_views.charts.weekly.chart_render.tmpl",
    "dashboard.js.chat.events.data_views.charts.weekly.summary.tmpl",
    "dashboard.js.chat.events.data_views.charts.weekly.tmpl",
    "dashboard.js.chat.events.data_views.history_fetch.chat_notifications.tmpl",
    "dashboard.js.chat.events.data_views.history_fetch.node_history_pipeline.tmpl",
    "dashboard.js.chat.events.data_views.history_fetch.summary_hydration.tmpl",
    "dashboard.js.chat.events.data_views.history_fetch.render_traffic_tables.tmpl",
    "dashboard.js.chat.events.data_views.history_fetch.tmpl",
    "dashboard.js.chat.render.identity_reactions.tmpl",
    "dashboard.js.chat.render.feed_prep.tmpl",
    "dashboard.js.chat.render.feed_items.tmpl",
    "dashboard.js.chat.render.roster_finalize.tmpl",
    "dashboard.js.chat.render.tmpl",
    "dashboard.js.runtime.views.packet_channels.channels_view.tmpl",
    "dashboard.js.runtime.views.packet_channels.encryption_rows.tmpl",
    "dashboard.js.runtime.views.packet_channels.encryption_trend.tmpl",
    "dashboard.js.runtime.views.encryption.tmpl",
    "dashboard.js.runtime.views.raw_data.tmpl",
    "dashboard.js.runtime.views.remote.tmpl",
    "dashboard.js.runtime.poll.tmpl",
    "dashboard.js.runtime.boot.tmpl",
    "dashboard.js.runtime.gui_benchmark.tmpl",
)


_CORE_UI_STUB_TEMPLATE = "dashboard.js.profile.core_ui.noop_feature_hooks.tmpl"
_RUNTIME_BOOT_TEMPLATE = "dashboard.js.runtime.boot.tmpl"


def _template_parts_for_profile() -> tuple[str, ...]:
    selected = list(_DASHBOARD_JS_TEMPLATE_PARTS)
    if _CORE_UI_STUB_TEMPLATE not in selected:
        try:
            runtime_boot_idx = selected.index(_RUNTIME_BOOT_TEMPLATE)
        except ValueError:
            runtime_boot_idx = len(selected)
        selected.insert(runtime_boot_idx, _CORE_UI_STUB_TEMPLATE)
    return tuple(selected)


def build_dashboard_js(
    *,
    refresh_ms: int,
    node_history_hours: int,
    node_history_max_points: int,
    reset_ticker_scale_on_restart: bool = True,
    debug_mode: bool = False,
    file_transfer_enabled: bool = False,
    file_transfer_auto_accept: bool = False,
    games_enabled: bool = False,
    file_transfer_max_bytes: int = _DEFAULT_FILE_TRANSFER_MAX_BYTES,
) -> str:
    selected_parts = _template_parts_for_profile()
    try:
        parsed_file_transfer_max_bytes = int(file_transfer_max_bytes)
    except (TypeError, ValueError):
        parsed_file_transfer_max_bytes = int(_DEFAULT_FILE_TRANSFER_MAX_BYTES)
    normalized_chat_max_bytes = max(1, int(_DEFAULT_CHAT_MAX_BYTES))
    normalized_file_transfer_max_bytes = max(
        int(_MIN_FILE_TRANSFER_MAX_BYTES),
        min(int(_MAX_FILE_TRANSFER_MAX_BYTES), parsed_file_transfer_max_bytes),
    )
    values = {
        "refresh_ms": refresh_ms,
        "node_history_hours": node_history_hours,
        "node_history_max_points": node_history_max_points,
        "reset_ticker_scale_on_restart": (
            1 if bool(reset_ticker_scale_on_restart) else 0
        ),
        "debug_mode_enabled": 1 if bool(debug_mode) else 0,
        "chat_max_bytes": normalized_chat_max_bytes,
        "file_transfer_enabled": 1 if bool(file_transfer_enabled) else 0,
        "file_transfer_auto_accept": 1 if bool(file_transfer_auto_accept) else 0,
        "games_enabled": 1 if bool(games_enabled) else 0,
        "file_transfer_max_bytes": normalized_file_transfer_max_bytes,
    }
    return "".join(
        _render_asset_template_helper(template_name, **values)
        for template_name in selected_parts
    )
