import re
from pathlib import Path

from meshdash.html_assets import render_asset_template


_ASSETS_DIR = Path(__file__).resolve().parents[1] / "meshdash" / "assets"
_SINGLE_TEMPLATE_TOKEN_RE = re.compile(r"(?<![${])\{([a-z_][a-z0-9_]*)\}")

_EXPECTED_TEMPLATE_TOKENS = {
    "dashboard.css.tmpl": set(),
    "dashboard.css.base.tmpl": {"theme_css"},
    "dashboard.css.layout.tmpl": set(),
    "dashboard.css.components.tmpl": set(),
    "dashboard.js.tmpl": {
        "refresh_ms",
        "node_history_hours",
        "node_history_max_points",
        "reset_ticker_scale_on_restart",
    },
    "dashboard.js.bootstrap.tmpl": set(),
    "dashboard.js.bootstrap.map.setup_emoji.base.tmpl": {
        "refresh_ms",
        "node_history_hours",
        "node_history_max_points",
        "reset_ticker_scale_on_restart",
    },
    "dashboard.js.bootstrap.map.setup_emoji.catalog.tmpl": set(),
    "dashboard.js.bootstrap.map.setup_emoji.state.constants_core.tmpl": set(),
    "dashboard.js.bootstrap.map.setup_emoji.state.runtime_primary.tmpl": set(),
    "dashboard.js.bootstrap.map.setup_emoji.state.runtime_games_chat.tmpl": set(),
    "dashboard.js.bootstrap.map.setup_emoji.state.runtime_map_history.tmpl": set(),
    "dashboard.js.bootstrap.map.setup_emoji.state.tmpl": set(),
    "dashboard.js.bootstrap.map.setup_emoji.tmpl": set(),
    "dashboard.js.bootstrap.map.offline_basemap.atlas_prep.tmpl": set(),
    "dashboard.js.bootstrap.map.offline_basemap.atlas_layers.tmpl": set(),
    "dashboard.js.bootstrap.map.offline_basemap.mode_connectivity.tmpl": set(),
    "dashboard.js.bootstrap.map.offline_basemap.tmpl": set(),
    "dashboard.js.bootstrap.map.resize.tmpl": set(),
    "dashboard.js.bootstrap.map.signal_heatmap.primitives_knobs.tmpl": set(),
    "dashboard.js.bootstrap.map.signal_heatmap.scoring.tmpl": set(),
    "dashboard.js.bootstrap.map.signal_heatmap.render_sync.tmpl": set(),
    "dashboard.js.bootstrap.map.signal_heatmap.tmpl": set(),
    "dashboard.js.bootstrap.map.wheel.tmpl": set(),
    "dashboard.js.bootstrap.map.tmpl": set(),
    "dashboard.js.bootstrap.tickers.metrics.core.tmpl": set(),
    "dashboard.js.bootstrap.tickers.metrics.runtime_time.tmpl": set(),
    "dashboard.js.bootstrap.tickers.metrics.theme.tmpl": set(),
    "dashboard.js.bootstrap.tickers.metrics.tmpl": set(),
    "dashboard.js.bootstrap.tickers.preferences.tmpl": set(),
    "dashboard.js.bootstrap.tickers.controls.settings_ui.tmpl": set(),
    "dashboard.js.bootstrap.tickers.controls.bindings_metric.tmpl": set(),
    "dashboard.js.bootstrap.tickers.controls.preferences_map_lines.tmpl": set(),
    "dashboard.js.bootstrap.tickers.controls.signal_heatmap_controls.tmpl": set(),
    "dashboard.js.bootstrap.tickers.controls.tmpl": set(),
    "dashboard.js.bootstrap.tickers.tmpl": set(),
    "dashboard.js.bootstrap.shared.chat_time_utils.tmpl": set(),
    "dashboard.js.bootstrap.shared.telemetry_local.tmpl": set(),
    "dashboard.js.bootstrap.shared.ticker_signal_gps.tmpl": set(),
    "dashboard.js.bootstrap.shared.ticker_node_system.tmpl": set(),
    "dashboard.js.bootstrap.shared.radio_status_freshness.tmpl": set(),
    "dashboard.js.bootstrap.shared.tmpl": set(),
    "dashboard.js.ui.shared_controls.tmpl": set(),
    "dashboard.js.chat.tmpl": set(),
    "dashboard.js.chat.state.tmpl": set(),
    "dashboard.js.chat.state.core.chat.delivery_reactions.telemetry_geo.tmpl": set(),
    "dashboard.js.chat.state.core.chat.delivery_reactions.ack_delivery.tmpl": set(),
    "dashboard.js.chat.state.core.chat.delivery_reactions.reaction_popover.tmpl": set(),
    "dashboard.js.chat.state.core.chat.delivery_reactions.tmpl": set(),
    "dashboard.js.chat.state.core.chat.channels_notifications.tmpl": set(),
    "dashboard.js.chat.state.core.chat.bot_quick_actions.tmpl": set(),
    "dashboard.js.chat.state.core.chat.tmpl": set(),
    "dashboard.js.chat.state.core.bot_history.sniffer_ingest.tmpl": set(),
    "dashboard.js.chat.state.core.bot_history.history_store.tmpl": set(),
    "dashboard.js.chat.state.core.bot_history.history_response_sync.tmpl": set(),
    "dashboard.js.chat.state.core.bot_history.settings_tabs_ui.tmpl": set(),
    "dashboard.js.chat.state.core.bot_history.sniffer_tab.tmpl": set(),
    "dashboard.js.chat.state.core.bot_history.tmpl": set(),
    "dashboard.js.chat.state.core.bot_controls.tmpl": set(),
    "dashboard.js.chat.state.core.tmpl": set(),
    "dashboard.js.chat.state.channels.labels_menu.tmpl": set(),
    "dashboard.js.chat.state.channels.options_controls.tmpl": set(),
    "dashboard.js.chat.state.channels.bindings_modes.tmpl": set(),
    "dashboard.js.chat.state.channels.tmpl": set(),
    "dashboard.js.chat.state.games.tmpl": set(),
    "dashboard.js.chat.state.games.reversi_local.protocol_invites.tmpl": set(),
    "dashboard.js.chat.state.games.reversi_local.board_state.tmpl": set(),
    "dashboard.js.chat.state.games.reversi_local.persistence_refresh.tmpl": set(),
    "dashboard.js.chat.state.games.reversi_local.tmpl": set(),
    "dashboard.js.chat.state.games.classic.checkers.helpers_moves.tmpl": set(),
    "dashboard.js.chat.state.games.classic.checkers.state_refresh.tmpl": set(),
    "dashboard.js.chat.state.games.classic.checkers.move_handlers.tmpl": set(),
    "dashboard.js.chat.state.games.classic.checkers.render_status.tmpl": set(),
    "dashboard.js.chat.state.games.classic.checkers.tmpl": set(),
    "dashboard.js.chat.state.games.classic.chess.tmpl": set(),
    "dashboard.js.chat.state.games.classic.poker.setup.tmpl": set(),
    "dashboard.js.chat.state.games.classic.poker.flow.round_setup.tmpl": set(),
    "dashboard.js.chat.state.games.classic.poker.flow.hand_eval_showdown.tmpl": set(),
    "dashboard.js.chat.state.games.classic.poker.flow.actions_draw.tmpl": set(),
    "dashboard.js.chat.state.games.classic.poker.flow.lifecycle_controls.tmpl": set(),
    "dashboard.js.chat.state.games.classic.poker.flow.tmpl": set(),
    "dashboard.js.chat.state.games.classic.poker.render.tmpl": set(),
    "dashboard.js.chat.state.games.classic.poker.tmpl": set(),
    "dashboard.js.chat.state.games.classic.tmpl": set(),
    "dashboard.js.chat.state.games.network.board_links.core.tmpl": set(),
    "dashboard.js.chat.state.games.network.board_links.sync_ui.tmpl": set(),
    "dashboard.js.chat.state.games.network.board_links.actions.tmpl": set(),
    "dashboard.js.chat.state.games.network.board_links.tmpl": set(),
    "dashboard.js.chat.state.games.network.reversi_link.protocol_sync.tmpl": set(),
    "dashboard.js.chat.state.games.network.reversi_link.move_runtime.tmpl": set(),
    "dashboard.js.chat.state.games.network.reversi_link.render_controls.tmpl": set(),
    "dashboard.js.chat.state.games.network.reversi_link.session_actions.tmpl": set(),
    "dashboard.js.chat.state.games.network.reversi_link.tmpl": set(),
    "dashboard.js.chat.state.games.network.tmpl": set(),
    "dashboard.js.chat.state.games.ui.tmpl": set(),
    "dashboard.js.chat.state.messaging.tmpl": set(),
    "dashboard.js.chat.state.messaging.peers.tmpl": set(),
    "dashboard.js.chat.state.messaging.emoji_search.tmpl": set(),
    "dashboard.js.chat.state.messaging.send_flow.tmpl": set(),
    "dashboard.js.chat.state.messaging.emoji_ui.tmpl": set(),
    "dashboard.js.chat.state.files.protocol.codec_flow.tmpl": set(),
    "dashboard.js.chat.state.files.protocol.ui_send.tmpl": set(),
    "dashboard.js.chat.state.files.protocol.session_state.tmpl": set(),
    "dashboard.js.chat.state.files.protocol.tmpl": set(),
    "dashboard.js.chat.state.files.frames.collect_state.tmpl": set(),
    "dashboard.js.chat.state.files.frames.rows_build.tmpl": set(),
    "dashboard.js.chat.state.files.frames.ack_match_helpers.tmpl": set(),
    "dashboard.js.chat.state.files.frames.tmpl": set(),
    "dashboard.js.chat.state.files.maintenance.ack_frames.tmpl": set(),
    "dashboard.js.chat.state.files.maintenance.outgoing_sessions.tmpl": set(),
    "dashboard.js.chat.state.files.maintenance.runner.tmpl": set(),
    "dashboard.js.chat.state.files.maintenance.tmpl": set(),
    "dashboard.js.chat.state.files.view.tmpl": set(),
    "dashboard.js.chat.state.files.tmpl": set(),
    "dashboard.js.chat.events.tmpl": set(),
    "dashboard.js.chat.events.core.tmpl": set(),
    "dashboard.js.chat.events.core.identity.node_self.tmpl": set(),
    "dashboard.js.chat.events.core.identity.favorites_selection.search_dropdowns.tmpl": set(),
    "dashboard.js.chat.events.core.identity.favorites_selection.favorites_state_ui.tmpl": set(),
    "dashboard.js.chat.events.core.identity.favorites_selection.selection_cache.tmpl": set(),
    "dashboard.js.chat.events.core.identity.favorites_selection.topbar_map_title.tmpl": set(),
    "dashboard.js.chat.events.core.identity.favorites_selection.tmpl": set(),
    "dashboard.js.chat.events.core.identity.text_utils.tmpl": set(),
    "dashboard.js.chat.events.core.identity.tmpl": set(),
    "dashboard.js.chat.events.core.layout_tables.split_state_loaders.tmpl": set(),
    "dashboard.js.chat.events.core.layout_tables.resizable_columns.tmpl": set(),
    "dashboard.js.chat.events.core.layout_tables.split_state_persist.tmpl": set(),
    "dashboard.js.chat.events.core.layout_tables.tmpl": set(),
    "dashboard.js.chat.events.core.notifications.notices.message_preview_history.tmpl": set(),
    "dashboard.js.chat.events.core.notifications.notices.persist_track.tmpl": set(),
    "dashboard.js.chat.events.core.notifications.notices.notification_counts.tmpl": set(),
    "dashboard.js.chat.events.core.notifications.notices.autodismiss_filters.tmpl": set(),
    "dashboard.js.chat.events.core.notifications.notices.tmpl": set(),
    "dashboard.js.chat.events.core.notifications.menus.tmpl": set(),
    "dashboard.js.chat.events.core.notifications.unread.tmpl": set(),
    "dashboard.js.chat.events.core.notifications.tmpl": set(),
    "dashboard.js.chat.events.core.navigation.layout.tmpl": set(),
    "dashboard.js.chat.events.core.navigation.splitters.tmpl": set(),
    "dashboard.js.chat.events.core.navigation.tablesort.tmpl": set(),
    "dashboard.js.chat.events.core.navigation.tmpl": set(),
    "dashboard.js.chat.events.console.tmpl": set(),
    "dashboard.js.chat.events.console.session.core.tmpl": set(),
    "dashboard.js.chat.events.console.session.state.tmpl": set(),
    "dashboard.js.chat.events.console.session.interaction.tmpl": set(),
    "dashboard.js.chat.events.console.session.tmpl": set(),
    "dashboard.js.chat.events.console.commands.helpers.tmpl": set(),
    "dashboard.js.chat.events.console.commands.registry.tmpl": set(),
    "dashboard.js.chat.events.console.commands.tmpl": set(),
    "dashboard.js.chat.events.console.formatting.tmpl": set(),
    "dashboard.js.chat.events.console.ui.tmpl": set(),
    "dashboard.js.chat.events.settings_map.tmpl": set(),
    "dashboard.js.chat.events.settings.tmpl": set(),
    "dashboard.js.chat.events.settings.state_normalize.cache_identity.tmpl": set(),
    "dashboard.js.chat.events.settings.state_normalize.accessors_extractors.tmpl": set(),
    "dashboard.js.chat.events.settings.state_normalize.normalize_helpers.tmpl": set(),
    "dashboard.js.chat.events.settings.state_normalize.editors_tabs_geo.tmpl": set(),
    "dashboard.js.chat.events.settings.state_normalize.core.tmpl": set(),
    "dashboard.js.chat.events.settings.state_normalize.position_map.source_cache_parsing.tmpl": set(),
    "dashboard.js.chat.events.settings.state_normalize.position_map.state_resolution.tmpl": set(),
    "dashboard.js.chat.events.settings.state_normalize.position_map.ui_bootstrap_tiles.tmpl": set(),
    "dashboard.js.chat.events.settings.state_normalize.position_map.input_sync_render.tmpl": set(),
    "dashboard.js.chat.events.settings.state_normalize.position_map.tmpl": set(),
    "dashboard.js.chat.events.settings.state_normalize.render_read.tmpl": set(),
    "dashboard.js.chat.events.settings.state_normalize.tmpl": set(),
    "dashboard.js.chat.events.settings.channels.table.tmpl": set(),
    "dashboard.js.chat.events.settings.channels.reading.tmpl": set(),
    "dashboard.js.chat.events.settings.channels.parse.tmpl": set(),
    "dashboard.js.chat.events.settings.channels.tmpl": set(),
    "dashboard.js.chat.events.settings.apply_actions.config.tmpl": set(),
    "dashboard.js.chat.events.settings.apply_actions.modules.tmpl": set(),
    "dashboard.js.chat.events.settings.apply_actions.radio_ops.tmpl": set(),
    "dashboard.js.chat.events.settings.apply_actions.tmpl": set(),
    "dashboard.js.chat.events.settings.bindings.tmpl": set(),
    "dashboard.js.chat.events.map_selection.tmpl": set(),
    "dashboard.js.chat.events.bindings.tmpl": set(),
    "dashboard.js.chat.events.data_views.tmpl": set(),
    "dashboard.js.chat.events.data_views.summary_map.summary.tmpl": set(),
    "dashboard.js.chat.events.data_views.summary_map.map_helpers.tmpl": set(),
    "dashboard.js.chat.events.data_views.summary_map.map_render.tmpl": set(),
    "dashboard.js.chat.events.data_views.summary_map.tmpl": set(),
    "dashboard.js.chat.events.data_views.nodes_saved.nodes_table.tmpl": set(),
    "dashboard.js.chat.events.data_views.nodes_saved.saved_helpers.tmpl": set(),
    "dashboard.js.chat.events.data_views.nodes_saved.saved_views.tmpl": set(),
    "dashboard.js.chat.events.data_views.nodes_saved.tmpl": set(),
    "dashboard.js.chat.events.data_views.charts.zoom_timeline.signal_zoom.tmpl": set(),
    "dashboard.js.chat.events.data_views.charts.zoom_timeline.history_trend_zoom.tmpl": set(),
    "dashboard.js.chat.events.data_views.charts.zoom_timeline.timeline_render.tmpl": set(),
    "dashboard.js.chat.events.data_views.charts.zoom_timeline.signal_timeline.tmpl": set(),
    "dashboard.js.chat.events.data_views.charts.zoom_timeline.tmpl": set(),
    "dashboard.js.chat.events.data_views.charts.signal_online.tmpl": set(),
    "dashboard.js.chat.events.data_views.charts.weekly.states.tmpl": set(),
    "dashboard.js.chat.events.data_views.charts.weekly.chart_render.tmpl": set(),
    "dashboard.js.chat.events.data_views.charts.weekly.summary.tmpl": set(),
    "dashboard.js.chat.events.data_views.charts.weekly.tmpl": set(),
    "dashboard.js.chat.events.data_views.charts.tmpl": set(),
    "dashboard.js.chat.events.data_views.history_fetch.chat_notifications.tmpl": set(),
    "dashboard.js.chat.events.data_views.history_fetch.node_history_pipeline.tmpl": set(),
    "dashboard.js.chat.events.data_views.history_fetch.summary_hydration.tmpl": set(),
    "dashboard.js.chat.events.data_views.history_fetch.render_traffic_tables.tmpl": set(),
    "dashboard.js.chat.events.data_views.history_fetch.tmpl": set(),
    "dashboard.js.chat.render.identity_reactions.tmpl": set(),
    "dashboard.js.chat.render.feed_prep.tmpl": set(),
    "dashboard.js.chat.render.feed_items.tmpl": set(),
    "dashboard.js.chat.render.roster_finalize.tmpl": set(),
    "dashboard.js.chat.render.tmpl": set(),
    "dashboard.js.runtime.tmpl": set(),
    "dashboard.js.runtime.views.tmpl": set(),
    "dashboard.js.runtime.views.packet_channels.channels_view.tmpl": set(),
    "dashboard.js.runtime.views.packet_channels.encryption_rows.tmpl": set(),
    "dashboard.js.runtime.views.packet_channels.encryption_trend.tmpl": set(),
    "dashboard.js.runtime.views.packet_channels.tmpl": set(),
    "dashboard.js.runtime.views.encryption.tmpl": set(),
    "dashboard.js.runtime.views.raw_data.tmpl": set(),
    "dashboard.js.runtime.poll.tmpl": set(),
    "dashboard.js.runtime.boot.tmpl": set(),
    "dashboard.html.tmpl": {
        "app_title",
        "app_heading",
        "style_css",
        "app_js",
        "revision_title",
        "revision_label",
        "safety_label",
        "packet_limit",
        "history_label",
        "refresh_ms",
    },
}


def _template_tokens(template_name: str) -> set[str]:
    raw = (_ASSETS_DIR / template_name).read_text(encoding="utf-8")
    return set(_SINGLE_TEMPLATE_TOKEN_RE.findall(raw))


def test_asset_templates_expose_only_expected_tokens():
    for template_name, expected_tokens in _EXPECTED_TEMPLATE_TOKENS.items():
        assert _template_tokens(template_name) == expected_tokens


def test_rendered_asset_templates_leave_no_single_token_placeholders():
    render_values = {
        "dashboard.css.tmpl": {},
        "dashboard.css.base.tmpl": {
            "theme_css": ":root { --unit-test-token: #123456; }",
        },
        "dashboard.css.layout.tmpl": {},
        "dashboard.css.components.tmpl": {},
        "dashboard.js.tmpl": {
            "refresh_ms": 3000,
            "node_history_hours": 72,
            "node_history_max_points": 1440,
            "reset_ticker_scale_on_restart": 1,
        },
        "dashboard.js.bootstrap.tmpl": {},
        "dashboard.js.bootstrap.map.setup_emoji.base.tmpl": {
            "refresh_ms": 3000,
            "node_history_hours": 72,
            "node_history_max_points": 1440,
            "reset_ticker_scale_on_restart": 1,
        },
        "dashboard.js.bootstrap.map.setup_emoji.catalog.tmpl": {},
        "dashboard.js.bootstrap.map.setup_emoji.state.constants_core.tmpl": {},
        "dashboard.js.bootstrap.map.setup_emoji.state.runtime_primary.tmpl": {},
        "dashboard.js.bootstrap.map.setup_emoji.state.runtime_games_chat.tmpl": {},
        "dashboard.js.bootstrap.map.setup_emoji.state.runtime_map_history.tmpl": {},
        "dashboard.js.bootstrap.map.setup_emoji.state.tmpl": {},
        "dashboard.js.bootstrap.map.setup_emoji.tmpl": {
            "refresh_ms": 3000,
            "node_history_hours": 72,
            "node_history_max_points": 1440,
            "reset_ticker_scale_on_restart": 1,
        },
        "dashboard.js.bootstrap.map.offline_basemap.atlas_prep.tmpl": {},
        "dashboard.js.bootstrap.map.offline_basemap.atlas_layers.tmpl": {},
        "dashboard.js.bootstrap.map.offline_basemap.mode_connectivity.tmpl": {},
        "dashboard.js.bootstrap.map.offline_basemap.tmpl": {},
        "dashboard.js.bootstrap.map.resize.tmpl": {},
        "dashboard.js.bootstrap.map.signal_heatmap.primitives_knobs.tmpl": {},
        "dashboard.js.bootstrap.map.signal_heatmap.scoring.tmpl": {},
        "dashboard.js.bootstrap.map.signal_heatmap.render_sync.tmpl": {},
        "dashboard.js.bootstrap.map.signal_heatmap.tmpl": {},
        "dashboard.js.bootstrap.map.wheel.tmpl": {},
        "dashboard.js.bootstrap.map.tmpl": {},
        "dashboard.js.bootstrap.tickers.metrics.core.tmpl": {},
        "dashboard.js.bootstrap.tickers.metrics.runtime_time.tmpl": {},
        "dashboard.js.bootstrap.tickers.metrics.theme.tmpl": {},
        "dashboard.js.bootstrap.tickers.metrics.tmpl": {},
        "dashboard.js.bootstrap.tickers.preferences.tmpl": {},
        "dashboard.js.bootstrap.tickers.controls.settings_ui.tmpl": {},
        "dashboard.js.bootstrap.tickers.controls.bindings_metric.tmpl": {},
        "dashboard.js.bootstrap.tickers.controls.preferences_map_lines.tmpl": {},
        "dashboard.js.bootstrap.tickers.controls.signal_heatmap_controls.tmpl": {},
        "dashboard.js.bootstrap.tickers.controls.tmpl": {},
        "dashboard.js.bootstrap.tickers.tmpl": {},
        "dashboard.js.bootstrap.shared.chat_time_utils.tmpl": {},
        "dashboard.js.bootstrap.shared.telemetry_local.tmpl": {},
        "dashboard.js.bootstrap.shared.ticker_signal_gps.tmpl": {},
        "dashboard.js.bootstrap.shared.ticker_node_system.tmpl": {},
        "dashboard.js.bootstrap.shared.radio_status_freshness.tmpl": {},
        "dashboard.js.bootstrap.shared.tmpl": {},
        "dashboard.js.ui.shared_controls.tmpl": {},
        "dashboard.js.chat.tmpl": {},
        "dashboard.js.chat.state.tmpl": {},
        "dashboard.js.chat.state.core.chat.delivery_reactions.telemetry_geo.tmpl": {},
        "dashboard.js.chat.state.core.chat.delivery_reactions.ack_delivery.tmpl": {},
        "dashboard.js.chat.state.core.chat.delivery_reactions.reaction_popover.tmpl": {},
        "dashboard.js.chat.state.core.chat.delivery_reactions.tmpl": {},
        "dashboard.js.chat.state.core.chat.channels_notifications.tmpl": {},
        "dashboard.js.chat.state.core.chat.bot_quick_actions.tmpl": {},
        "dashboard.js.chat.state.core.chat.tmpl": {},
        "dashboard.js.chat.state.core.bot_history.sniffer_ingest.tmpl": {},
        "dashboard.js.chat.state.core.bot_history.history_store.tmpl": {},
        "dashboard.js.chat.state.core.bot_history.history_response_sync.tmpl": {},
        "dashboard.js.chat.state.core.bot_history.settings_tabs_ui.tmpl": {},
        "dashboard.js.chat.state.core.bot_history.sniffer_tab.tmpl": {},
        "dashboard.js.chat.state.core.bot_history.tmpl": {},
        "dashboard.js.chat.state.core.bot_controls.tmpl": {},
        "dashboard.js.chat.state.core.tmpl": {},
        "dashboard.js.chat.state.channels.labels_menu.tmpl": {},
        "dashboard.js.chat.state.channels.options_controls.tmpl": {},
        "dashboard.js.chat.state.channels.bindings_modes.tmpl": {},
        "dashboard.js.chat.state.channels.tmpl": {},
        "dashboard.js.chat.state.games.tmpl": {},
        "dashboard.js.chat.state.games.reversi_local.protocol_invites.tmpl": {},
        "dashboard.js.chat.state.games.reversi_local.board_state.tmpl": {},
        "dashboard.js.chat.state.games.reversi_local.persistence_refresh.tmpl": {},
        "dashboard.js.chat.state.games.reversi_local.tmpl": {},
        "dashboard.js.chat.state.games.classic.checkers.helpers_moves.tmpl": {},
        "dashboard.js.chat.state.games.classic.checkers.state_refresh.tmpl": {},
        "dashboard.js.chat.state.games.classic.checkers.move_handlers.tmpl": {},
        "dashboard.js.chat.state.games.classic.checkers.render_status.tmpl": {},
        "dashboard.js.chat.state.games.classic.checkers.tmpl": {},
        "dashboard.js.chat.state.games.classic.chess.tmpl": {},
        "dashboard.js.chat.state.games.classic.poker.setup.tmpl": {},
        "dashboard.js.chat.state.games.classic.poker.flow.round_setup.tmpl": {},
        "dashboard.js.chat.state.games.classic.poker.flow.hand_eval_showdown.tmpl": {},
        "dashboard.js.chat.state.games.classic.poker.flow.actions_draw.tmpl": {},
        "dashboard.js.chat.state.games.classic.poker.flow.lifecycle_controls.tmpl": {},
        "dashboard.js.chat.state.games.classic.poker.flow.tmpl": {},
        "dashboard.js.chat.state.games.classic.poker.render.tmpl": {},
        "dashboard.js.chat.state.games.classic.poker.tmpl": {},
        "dashboard.js.chat.state.games.classic.tmpl": {},
        "dashboard.js.chat.state.games.network.board_links.core.tmpl": {},
        "dashboard.js.chat.state.games.network.board_links.sync_ui.tmpl": {},
        "dashboard.js.chat.state.games.network.board_links.actions.tmpl": {},
        "dashboard.js.chat.state.games.network.board_links.tmpl": {},
        "dashboard.js.chat.state.games.network.reversi_link.protocol_sync.tmpl": {},
        "dashboard.js.chat.state.games.network.reversi_link.move_runtime.tmpl": {},
        "dashboard.js.chat.state.games.network.reversi_link.render_controls.tmpl": {},
        "dashboard.js.chat.state.games.network.reversi_link.session_actions.tmpl": {},
        "dashboard.js.chat.state.games.network.reversi_link.tmpl": {},
        "dashboard.js.chat.state.games.network.tmpl": {},
        "dashboard.js.chat.state.games.ui.tmpl": {},
        "dashboard.js.chat.state.messaging.tmpl": {},
        "dashboard.js.chat.state.messaging.peers.tmpl": {},
        "dashboard.js.chat.state.messaging.emoji_search.tmpl": {},
        "dashboard.js.chat.state.messaging.send_flow.tmpl": {},
        "dashboard.js.chat.state.messaging.emoji_ui.tmpl": {},
        "dashboard.js.chat.state.files.protocol.codec_flow.tmpl": {},
        "dashboard.js.chat.state.files.protocol.ui_send.tmpl": {},
        "dashboard.js.chat.state.files.protocol.session_state.tmpl": {},
        "dashboard.js.chat.state.files.protocol.tmpl": {},
        "dashboard.js.chat.state.files.frames.collect_state.tmpl": {},
        "dashboard.js.chat.state.files.frames.rows_build.tmpl": {},
        "dashboard.js.chat.state.files.frames.ack_match_helpers.tmpl": {},
        "dashboard.js.chat.state.files.frames.tmpl": {},
        "dashboard.js.chat.state.files.maintenance.ack_frames.tmpl": {},
        "dashboard.js.chat.state.files.maintenance.outgoing_sessions.tmpl": {},
        "dashboard.js.chat.state.files.maintenance.runner.tmpl": {},
        "dashboard.js.chat.state.files.maintenance.tmpl": {},
        "dashboard.js.chat.state.files.view.tmpl": {},
        "dashboard.js.chat.state.files.tmpl": {},
        "dashboard.js.chat.events.tmpl": {},
        "dashboard.js.chat.events.core.tmpl": {},
        "dashboard.js.chat.events.core.identity.node_self.tmpl": {},
        "dashboard.js.chat.events.core.identity.favorites_selection.search_dropdowns.tmpl": {},
        "dashboard.js.chat.events.core.identity.favorites_selection.favorites_state_ui.tmpl": {},
        "dashboard.js.chat.events.core.identity.favorites_selection.selection_cache.tmpl": {},
        "dashboard.js.chat.events.core.identity.favorites_selection.topbar_map_title.tmpl": {},
        "dashboard.js.chat.events.core.identity.favorites_selection.tmpl": {},
        "dashboard.js.chat.events.core.identity.text_utils.tmpl": {},
        "dashboard.js.chat.events.core.identity.tmpl": {},
        "dashboard.js.chat.events.core.layout_tables.split_state_loaders.tmpl": {},
        "dashboard.js.chat.events.core.layout_tables.resizable_columns.tmpl": {},
        "dashboard.js.chat.events.core.layout_tables.split_state_persist.tmpl": {},
        "dashboard.js.chat.events.core.layout_tables.tmpl": {},
        "dashboard.js.chat.events.core.notifications.notices.message_preview_history.tmpl": {},
        "dashboard.js.chat.events.core.notifications.notices.persist_track.tmpl": {},
        "dashboard.js.chat.events.core.notifications.notices.notification_counts.tmpl": {},
        "dashboard.js.chat.events.core.notifications.notices.autodismiss_filters.tmpl": {},
        "dashboard.js.chat.events.core.notifications.notices.tmpl": {},
        "dashboard.js.chat.events.core.notifications.menus.tmpl": {},
        "dashboard.js.chat.events.core.notifications.unread.tmpl": {},
        "dashboard.js.chat.events.core.notifications.tmpl": {},
        "dashboard.js.chat.events.core.navigation.layout.tmpl": {},
        "dashboard.js.chat.events.core.navigation.splitters.tmpl": {},
        "dashboard.js.chat.events.core.navigation.tablesort.tmpl": {},
        "dashboard.js.chat.events.core.navigation.tmpl": {},
        "dashboard.js.chat.events.console.tmpl": {},
        "dashboard.js.chat.events.console.session.core.tmpl": {},
        "dashboard.js.chat.events.console.session.state.tmpl": {},
        "dashboard.js.chat.events.console.session.interaction.tmpl": {},
        "dashboard.js.chat.events.console.session.tmpl": {},
        "dashboard.js.chat.events.console.commands.helpers.tmpl": {},
        "dashboard.js.chat.events.console.commands.registry.tmpl": {},
        "dashboard.js.chat.events.console.commands.tmpl": {},
        "dashboard.js.chat.events.console.formatting.tmpl": {},
        "dashboard.js.chat.events.console.ui.tmpl": {},
        "dashboard.js.chat.events.settings_map.tmpl": {},
        "dashboard.js.chat.events.settings.tmpl": {},
        "dashboard.js.chat.events.settings.state_normalize.cache_identity.tmpl": {},
        "dashboard.js.chat.events.settings.state_normalize.accessors_extractors.tmpl": {},
        "dashboard.js.chat.events.settings.state_normalize.normalize_helpers.tmpl": {},
        "dashboard.js.chat.events.settings.state_normalize.editors_tabs_geo.tmpl": {},
        "dashboard.js.chat.events.settings.state_normalize.core.tmpl": {},
        "dashboard.js.chat.events.settings.state_normalize.position_map.source_cache_parsing.tmpl": {},
        "dashboard.js.chat.events.settings.state_normalize.position_map.state_resolution.tmpl": {},
        "dashboard.js.chat.events.settings.state_normalize.position_map.ui_bootstrap_tiles.tmpl": {},
        "dashboard.js.chat.events.settings.state_normalize.position_map.input_sync_render.tmpl": {},
        "dashboard.js.chat.events.settings.state_normalize.position_map.tmpl": {},
        "dashboard.js.chat.events.settings.state_normalize.render_read.tmpl": {},
        "dashboard.js.chat.events.settings.state_normalize.tmpl": {},
        "dashboard.js.chat.events.settings.channels.table.tmpl": {},
        "dashboard.js.chat.events.settings.channels.reading.tmpl": {},
        "dashboard.js.chat.events.settings.channels.parse.tmpl": {},
        "dashboard.js.chat.events.settings.channels.tmpl": {},
        "dashboard.js.chat.events.settings.apply_actions.config.tmpl": {},
        "dashboard.js.chat.events.settings.apply_actions.modules.tmpl": {},
        "dashboard.js.chat.events.settings.apply_actions.radio_ops.tmpl": {},
        "dashboard.js.chat.events.settings.apply_actions.tmpl": {},
        "dashboard.js.chat.events.settings.bindings.tmpl": {},
        "dashboard.js.chat.events.map_selection.tmpl": {},
        "dashboard.js.chat.events.bindings.tmpl": {},
        "dashboard.js.chat.events.data_views.tmpl": {},
        "dashboard.js.chat.events.data_views.summary_map.summary.tmpl": {},
        "dashboard.js.chat.events.data_views.summary_map.map_helpers.tmpl": {},
        "dashboard.js.chat.events.data_views.summary_map.map_render.tmpl": {},
        "dashboard.js.chat.events.data_views.summary_map.tmpl": {},
        "dashboard.js.chat.events.data_views.nodes_saved.nodes_table.tmpl": {},
        "dashboard.js.chat.events.data_views.nodes_saved.saved_helpers.tmpl": {},
        "dashboard.js.chat.events.data_views.nodes_saved.saved_views.tmpl": {},
        "dashboard.js.chat.events.data_views.nodes_saved.tmpl": {},
        "dashboard.js.chat.events.data_views.charts.zoom_timeline.signal_zoom.tmpl": {},
        "dashboard.js.chat.events.data_views.charts.zoom_timeline.history_trend_zoom.tmpl": {},
        "dashboard.js.chat.events.data_views.charts.zoom_timeline.timeline_render.tmpl": {},
        "dashboard.js.chat.events.data_views.charts.zoom_timeline.signal_timeline.tmpl": {},
        "dashboard.js.chat.events.data_views.charts.zoom_timeline.tmpl": {},
        "dashboard.js.chat.events.data_views.charts.signal_online.tmpl": {},
        "dashboard.js.chat.events.data_views.charts.weekly.states.tmpl": {},
        "dashboard.js.chat.events.data_views.charts.weekly.chart_render.tmpl": {},
        "dashboard.js.chat.events.data_views.charts.weekly.summary.tmpl": {},
        "dashboard.js.chat.events.data_views.charts.weekly.tmpl": {},
        "dashboard.js.chat.events.data_views.charts.tmpl": {},
        "dashboard.js.chat.events.data_views.history_fetch.chat_notifications.tmpl": {},
        "dashboard.js.chat.events.data_views.history_fetch.node_history_pipeline.tmpl": {},
        "dashboard.js.chat.events.data_views.history_fetch.summary_hydration.tmpl": {},
        "dashboard.js.chat.events.data_views.history_fetch.render_traffic_tables.tmpl": {},
        "dashboard.js.chat.events.data_views.history_fetch.tmpl": {},
        "dashboard.js.chat.render.identity_reactions.tmpl": {},
        "dashboard.js.chat.render.feed_prep.tmpl": {},
        "dashboard.js.chat.render.feed_items.tmpl": {},
        "dashboard.js.chat.render.roster_finalize.tmpl": {},
        "dashboard.js.chat.render.tmpl": {},
        "dashboard.js.runtime.tmpl": {},
        "dashboard.js.runtime.views.tmpl": {},
        "dashboard.js.runtime.views.packet_channels.channels_view.tmpl": {},
        "dashboard.js.runtime.views.packet_channels.encryption_rows.tmpl": {},
        "dashboard.js.runtime.views.packet_channels.encryption_trend.tmpl": {},
        "dashboard.js.runtime.views.packet_channels.tmpl": {},
        "dashboard.js.runtime.views.encryption.tmpl": {},
        "dashboard.js.runtime.views.raw_data.tmpl": {},
        "dashboard.js.runtime.poll.tmpl": {},
        "dashboard.js.runtime.boot.tmpl": {},
        "dashboard.html.tmpl": {
            "app_title": "Meshyface",
            "app_heading": "Meshyface",
            "style_css": "/* css */",
            "app_js": "// js",
            "revision_title": "Rev title",
            "revision_label": "Rev label",
            "safety_label": "Secrets redacted",
            "packet_limit": 250,
            "history_label": "History: on",
            "refresh_ms": 3000,
        },
    }

    for template_name, values in render_values.items():
        rendered = render_asset_template(template_name, **values)
        for token in _EXPECTED_TEMPLATE_TOKENS[template_name]:
            assert f"{{{token}}}" not in rendered
