import re
from pathlib import Path

from meshdash.html_assets import render_asset_template


_ASSETS_DIR = Path(__file__).resolve().parents[1] / "meshdash" / "assets"
_SINGLE_TEMPLATE_TOKEN_RE = re.compile(r"(?<![${])\{([a-z_][a-z0-9_]*)\}")

_EXPECTED_TEMPLATE_TOKENS = {
    "dashboard.css.tmpl": set(),
    "dashboard.css.base.tmpl": {"theme_css"},
    "dashboard.css.layout.tmpl": set(),
    "dashboard.css.components.tmpl": set(),
    "dashboard.js.tmpl": {
        "refresh_ms",
        "node_history_hours",
        "node_history_max_points",
        "reset_ticker_scale_on_restart",
    },
    "dashboard.js.bootstrap.tmpl": set(),
    "dashboard.js.bootstrap.map.setup_emoji.tmpl": {
        "refresh_ms",
        "node_history_hours",
        "node_history_max_points",
        "reset_ticker_scale_on_restart",
    },
    "dashboard.js.bootstrap.map.offline_basemap.tmpl": set(),
    "dashboard.js.bootstrap.map.resize.tmpl": set(),
    "dashboard.js.bootstrap.map.signal_heatmap.tmpl": set(),
    "dashboard.js.bootstrap.map.wheel.tmpl": set(),
    "dashboard.js.bootstrap.map.tmpl": set(),
    "dashboard.js.bootstrap.tickers.metrics.tmpl": set(),
    "dashboard.js.bootstrap.tickers.preferences.tmpl": set(),
    "dashboard.js.bootstrap.tickers.controls.tmpl": set(),
    "dashboard.js.bootstrap.tickers.tmpl": set(),
    "dashboard.js.bootstrap.shared.tmpl": set(),
    "dashboard.js.ui.shared_controls.tmpl": set(),
    "dashboard.js.chat.tmpl": set(),
    "dashboard.js.chat.state.tmpl": set(),
    "dashboard.js.chat.state.core.chat.delivery_reactions.tmpl": set(),
    "dashboard.js.chat.state.core.chat.channels_notifications.tmpl": set(),
    "dashboard.js.chat.state.core.chat.bot_quick_actions.tmpl": set(),
    "dashboard.js.chat.state.core.chat.tmpl": set(),
    "dashboard.js.chat.state.core.bot_history.tmpl": set(),
    "dashboard.js.chat.state.core.bot_controls.tmpl": set(),
    "dashboard.js.chat.state.core.tmpl": set(),
    "dashboard.js.chat.state.channels.tmpl": set(),
    "dashboard.js.chat.state.games.tmpl": set(),
    "dashboard.js.chat.state.games.reversi_local.tmpl": set(),
    "dashboard.js.chat.state.games.classic.checkers.tmpl": set(),
    "dashboard.js.chat.state.games.classic.chess.tmpl": set(),
    "dashboard.js.chat.state.games.classic.poker.setup.tmpl": set(),
    "dashboard.js.chat.state.games.classic.poker.flow.tmpl": set(),
    "dashboard.js.chat.state.games.classic.poker.render.tmpl": set(),
    "dashboard.js.chat.state.games.classic.poker.tmpl": set(),
    "dashboard.js.chat.state.games.classic.tmpl": set(),
    "dashboard.js.chat.state.games.network.board_links.tmpl": set(),
    "dashboard.js.chat.state.games.network.reversi_link.tmpl": set(),
    "dashboard.js.chat.state.games.network.tmpl": set(),
    "dashboard.js.chat.state.games.ui.tmpl": set(),
    "dashboard.js.chat.state.messaging.tmpl": set(),
    "dashboard.js.chat.state.messaging.peers.tmpl": set(),
    "dashboard.js.chat.state.messaging.emoji_search.tmpl": set(),
    "dashboard.js.chat.state.messaging.send_flow.tmpl": set(),
    "dashboard.js.chat.state.messaging.emoji_ui.tmpl": set(),
    "dashboard.js.chat.state.files.protocol.tmpl": set(),
    "dashboard.js.chat.state.files.frames.tmpl": set(),
    "dashboard.js.chat.state.files.maintenance.tmpl": set(),
    "dashboard.js.chat.state.files.view.tmpl": set(),
    "dashboard.js.chat.state.files.tmpl": set(),
    "dashboard.js.chat.events.tmpl": set(),
    "dashboard.js.chat.events.core.tmpl": set(),
    "dashboard.js.chat.events.core.identity.node_self.tmpl": set(),
    "dashboard.js.chat.events.core.identity.favorites_selection.tmpl": set(),
    "dashboard.js.chat.events.core.identity.text_utils.tmpl": set(),
    "dashboard.js.chat.events.core.identity.tmpl": set(),
    "dashboard.js.chat.events.core.layout_tables.tmpl": set(),
    "dashboard.js.chat.events.core.notifications.notices.tmpl": set(),
    "dashboard.js.chat.events.core.notifications.menus.tmpl": set(),
    "dashboard.js.chat.events.core.notifications.unread.tmpl": set(),
    "dashboard.js.chat.events.core.notifications.tmpl": set(),
    "dashboard.js.chat.events.core.navigation.layout.tmpl": set(),
    "dashboard.js.chat.events.core.navigation.splitters.tmpl": set(),
    "dashboard.js.chat.events.core.navigation.tablesort.tmpl": set(),
    "dashboard.js.chat.events.core.navigation.tmpl": set(),
    "dashboard.js.chat.events.console.tmpl": set(),
    "dashboard.js.chat.events.console.session.tmpl": set(),
    "dashboard.js.chat.events.console.commands.helpers.tmpl": set(),
    "dashboard.js.chat.events.console.commands.registry.tmpl": set(),
    "dashboard.js.chat.events.console.commands.tmpl": set(),
    "dashboard.js.chat.events.console.formatting.tmpl": set(),
    "dashboard.js.chat.events.console.ui.tmpl": set(),
    "dashboard.js.chat.events.settings_map.tmpl": set(),
    "dashboard.js.chat.events.settings.tmpl": set(),
    "dashboard.js.chat.events.settings.state_normalize.core.tmpl": set(),
    "dashboard.js.chat.events.settings.state_normalize.position_map.tmpl": set(),
    "dashboard.js.chat.events.settings.state_normalize.render_read.tmpl": set(),
    "dashboard.js.chat.events.settings.state_normalize.tmpl": set(),
    "dashboard.js.chat.events.settings.channels.table.tmpl": set(),
    "dashboard.js.chat.events.settings.channels.reading.tmpl": set(),
    "dashboard.js.chat.events.settings.channels.parse.tmpl": set(),
    "dashboard.js.chat.events.settings.channels.tmpl": set(),
    "dashboard.js.chat.events.settings.apply_actions.config.tmpl": set(),
    "dashboard.js.chat.events.settings.apply_actions.modules.tmpl": set(),
    "dashboard.js.chat.events.settings.apply_actions.radio_ops.tmpl": set(),
    "dashboard.js.chat.events.settings.apply_actions.tmpl": set(),
    "dashboard.js.chat.events.settings.bindings.tmpl": set(),
    "dashboard.js.chat.events.map_selection.tmpl": set(),
    "dashboard.js.chat.events.bindings.tmpl": set(),
    "dashboard.js.chat.events.data_views.tmpl": set(),
    "dashboard.js.chat.events.data_views.summary_map.summary.tmpl": set(),
    "dashboard.js.chat.events.data_views.summary_map.map_helpers.tmpl": set(),
    "dashboard.js.chat.events.data_views.summary_map.map_render.tmpl": set(),
    "dashboard.js.chat.events.data_views.summary_map.tmpl": set(),
    "dashboard.js.chat.events.data_views.nodes_saved.tmpl": set(),
    "dashboard.js.chat.events.data_views.charts.zoom_timeline.tmpl": set(),
    "dashboard.js.chat.events.data_views.charts.signal_online.tmpl": set(),
    "dashboard.js.chat.events.data_views.charts.weekly.tmpl": set(),
    "dashboard.js.chat.events.data_views.charts.tmpl": set(),
    "dashboard.js.chat.events.data_views.history_fetch.tmpl": set(),
    "dashboard.js.chat.render.tmpl": set(),
    "dashboard.js.runtime.tmpl": set(),
    "dashboard.js.runtime.views.tmpl": set(),
    "dashboard.js.runtime.views.packet_channels.tmpl": set(),
    "dashboard.js.runtime.views.encryption.tmpl": set(),
    "dashboard.js.runtime.views.raw_data.tmpl": set(),
    "dashboard.js.runtime.poll.tmpl": set(),
    "dashboard.js.runtime.boot.tmpl": set(),
    "dashboard.html.tmpl": {
        "app_title",
        "app_heading",
        "style_css",
        "app_js",
        "revision_title",
        "revision_label",
        "safety_label",
        "packet_limit",
        "history_label",
        "refresh_ms",
    },
}


def _template_tokens(template_name: str) -> set[str]:
    raw = (_ASSETS_DIR / template_name).read_text(encoding="utf-8")
    return set(_SINGLE_TEMPLATE_TOKEN_RE.findall(raw))


def test_asset_templates_expose_only_expected_tokens():
    for template_name, expected_tokens in _EXPECTED_TEMPLATE_TOKENS.items():
        assert _template_tokens(template_name) == expected_tokens


def test_rendered_asset_templates_leave_no_single_token_placeholders():
    render_values = {
        "dashboard.css.tmpl": {},
        "dashboard.css.base.tmpl": {
            "theme_css": ":root { --unit-test-token: #123456; }",
        },
        "dashboard.css.layout.tmpl": {},
        "dashboard.css.components.tmpl": {},
        "dashboard.js.tmpl": {
            "refresh_ms": 3000,
            "node_history_hours": 72,
            "node_history_max_points": 1440,
            "reset_ticker_scale_on_restart": 1,
        },
        "dashboard.js.bootstrap.tmpl": {},
        "dashboard.js.bootstrap.map.setup_emoji.tmpl": {
            "refresh_ms": 3000,
            "node_history_hours": 72,
            "node_history_max_points": 1440,
            "reset_ticker_scale_on_restart": 1,
        },
        "dashboard.js.bootstrap.map.offline_basemap.tmpl": {},
        "dashboard.js.bootstrap.map.resize.tmpl": {},
        "dashboard.js.bootstrap.map.signal_heatmap.tmpl": {},
        "dashboard.js.bootstrap.map.wheel.tmpl": {},
        "dashboard.js.bootstrap.map.tmpl": {},
        "dashboard.js.bootstrap.tickers.metrics.tmpl": {},
        "dashboard.js.bootstrap.tickers.preferences.tmpl": {},
        "dashboard.js.bootstrap.tickers.controls.tmpl": {},
        "dashboard.js.bootstrap.tickers.tmpl": {},
        "dashboard.js.bootstrap.shared.tmpl": {},
        "dashboard.js.ui.shared_controls.tmpl": {},
        "dashboard.js.chat.tmpl": {},
        "dashboard.js.chat.state.tmpl": {},
        "dashboard.js.chat.state.core.chat.delivery_reactions.tmpl": {},
        "dashboard.js.chat.state.core.chat.channels_notifications.tmpl": {},
        "dashboard.js.chat.state.core.chat.bot_quick_actions.tmpl": {},
        "dashboard.js.chat.state.core.chat.tmpl": {},
        "dashboard.js.chat.state.core.bot_history.tmpl": {},
        "dashboard.js.chat.state.core.bot_controls.tmpl": {},
        "dashboard.js.chat.state.core.tmpl": {},
        "dashboard.js.chat.state.channels.tmpl": {},
        "dashboard.js.chat.state.games.tmpl": {},
        "dashboard.js.chat.state.games.reversi_local.tmpl": {},
        "dashboard.js.chat.state.games.classic.checkers.tmpl": {},
        "dashboard.js.chat.state.games.classic.chess.tmpl": {},
        "dashboard.js.chat.state.games.classic.poker.setup.tmpl": {},
        "dashboard.js.chat.state.games.classic.poker.flow.tmpl": {},
        "dashboard.js.chat.state.games.classic.poker.render.tmpl": {},
        "dashboard.js.chat.state.games.classic.poker.tmpl": {},
        "dashboard.js.chat.state.games.classic.tmpl": {},
        "dashboard.js.chat.state.games.network.board_links.tmpl": {},
        "dashboard.js.chat.state.games.network.reversi_link.tmpl": {},
        "dashboard.js.chat.state.games.network.tmpl": {},
        "dashboard.js.chat.state.games.ui.tmpl": {},
        "dashboard.js.chat.state.messaging.tmpl": {},
        "dashboard.js.chat.state.messaging.peers.tmpl": {},
        "dashboard.js.chat.state.messaging.emoji_search.tmpl": {},
        "dashboard.js.chat.state.messaging.send_flow.tmpl": {},
        "dashboard.js.chat.state.messaging.emoji_ui.tmpl": {},
        "dashboard.js.chat.state.files.protocol.tmpl": {},
        "dashboard.js.chat.state.files.frames.tmpl": {},
        "dashboard.js.chat.state.files.maintenance.tmpl": {},
        "dashboard.js.chat.state.files.view.tmpl": {},
        "dashboard.js.chat.state.files.tmpl": {},
        "dashboard.js.chat.events.tmpl": {},
        "dashboard.js.chat.events.core.tmpl": {},
        "dashboard.js.chat.events.core.identity.node_self.tmpl": {},
        "dashboard.js.chat.events.core.identity.favorites_selection.tmpl": {},
        "dashboard.js.chat.events.core.identity.text_utils.tmpl": {},
        "dashboard.js.chat.events.core.identity.tmpl": {},
        "dashboard.js.chat.events.core.layout_tables.tmpl": {},
        "dashboard.js.chat.events.core.notifications.notices.tmpl": {},
        "dashboard.js.chat.events.core.notifications.menus.tmpl": {},
        "dashboard.js.chat.events.core.notifications.unread.tmpl": {},
        "dashboard.js.chat.events.core.notifications.tmpl": {},
        "dashboard.js.chat.events.core.navigation.layout.tmpl": {},
        "dashboard.js.chat.events.core.navigation.splitters.tmpl": {},
        "dashboard.js.chat.events.core.navigation.tablesort.tmpl": {},
        "dashboard.js.chat.events.core.navigation.tmpl": {},
        "dashboard.js.chat.events.console.tmpl": {},
        "dashboard.js.chat.events.console.session.tmpl": {},
        "dashboard.js.chat.events.console.commands.helpers.tmpl": {},
        "dashboard.js.chat.events.console.commands.registry.tmpl": {},
        "dashboard.js.chat.events.console.commands.tmpl": {},
        "dashboard.js.chat.events.console.formatting.tmpl": {},
        "dashboard.js.chat.events.console.ui.tmpl": {},
        "dashboard.js.chat.events.settings_map.tmpl": {},
        "dashboard.js.chat.events.settings.tmpl": {},
        "dashboard.js.chat.events.settings.state_normalize.core.tmpl": {},
        "dashboard.js.chat.events.settings.state_normalize.position_map.tmpl": {},
        "dashboard.js.chat.events.settings.state_normalize.render_read.tmpl": {},
        "dashboard.js.chat.events.settings.state_normalize.tmpl": {},
        "dashboard.js.chat.events.settings.channels.table.tmpl": {},
        "dashboard.js.chat.events.settings.channels.reading.tmpl": {},
        "dashboard.js.chat.events.settings.channels.parse.tmpl": {},
        "dashboard.js.chat.events.settings.channels.tmpl": {},
        "dashboard.js.chat.events.settings.apply_actions.config.tmpl": {},
        "dashboard.js.chat.events.settings.apply_actions.modules.tmpl": {},
        "dashboard.js.chat.events.settings.apply_actions.radio_ops.tmpl": {},
        "dashboard.js.chat.events.settings.apply_actions.tmpl": {},
        "dashboard.js.chat.events.settings.bindings.tmpl": {},
        "dashboard.js.chat.events.map_selection.tmpl": {},
        "dashboard.js.chat.events.bindings.tmpl": {},
        "dashboard.js.chat.events.data_views.tmpl": {},
        "dashboard.js.chat.events.data_views.summary_map.summary.tmpl": {},
        "dashboard.js.chat.events.data_views.summary_map.map_helpers.tmpl": {},
        "dashboard.js.chat.events.data_views.summary_map.map_render.tmpl": {},
        "dashboard.js.chat.events.data_views.summary_map.tmpl": {},
        "dashboard.js.chat.events.data_views.nodes_saved.tmpl": {},
        "dashboard.js.chat.events.data_views.charts.zoom_timeline.tmpl": {},
        "dashboard.js.chat.events.data_views.charts.signal_online.tmpl": {},
        "dashboard.js.chat.events.data_views.charts.weekly.tmpl": {},
        "dashboard.js.chat.events.data_views.charts.tmpl": {},
        "dashboard.js.chat.events.data_views.history_fetch.tmpl": {},
        "dashboard.js.chat.render.tmpl": {},
        "dashboard.js.runtime.tmpl": {},
        "dashboard.js.runtime.views.tmpl": {},
        "dashboard.js.runtime.views.packet_channels.tmpl": {},
        "dashboard.js.runtime.views.encryption.tmpl": {},
        "dashboard.js.runtime.views.raw_data.tmpl": {},
        "dashboard.js.runtime.poll.tmpl": {},
        "dashboard.js.runtime.boot.tmpl": {},
        "dashboard.html.tmpl": {
            "app_title": "Meshyface",
            "app_heading": "Meshyface",
            "style_css": "/* css */",
            "app_js": "// js",
            "revision_title": "Rev title",
            "revision_label": "Rev label",
            "safety_label": "Secrets redacted",
            "packet_limit": 250,
            "history_label": "History: on",
            "refresh_ms": 3000,
        },
    }

    for template_name, values in render_values.items():
        rendered = render_asset_template(template_name, **values)
        for token in _EXPECTED_TEMPLATE_TOKENS[template_name]:
            assert f"{{{token}}}" not in rendered
